import {getDistance} from 'geolib';

export const stateAbbreviations: any = {
  alabama: 'AL',
  alaska: 'AK',
  arizona: 'AZ',
  arkansas: 'AR',
  california: 'CA',
  colorado: 'CO',
  connecticut: 'CT',
  delaware: 'DE',
  florida: 'FL',
  georgia: 'GA',
  hawaii: 'HI',
  idaho: 'ID',
  illinois: 'IL',
  indiana: 'IN',
  iowa: 'IA',
  kansas: 'KS',
  kentucky: 'KY',
  louisiana: 'LA',
  maine: 'ME',
  maryland: 'MD',
  massachusetts: 'MA',
  michigan: 'MI',
  minnesota: 'MN',
  mississippi: 'MS',
  missouri: 'MO',
  montana: 'MT',
  nebraska: 'NE',
  nevada: 'NV',
  'new hampshire': 'NH',
  'new jersey': 'NJ',
  'new mexico': 'NM',
  'new york': 'NY',
  'north carolina': 'NC',
  'north dakota': 'ND',
  ohio: 'OH',
  oklahoma: 'OK',
  oregon: 'OR',
  pennsylvania: 'PA',
  'rhode Island': 'RI',
  'south Carolina': 'SC',
  'south Dakota': 'SD',
  tennessee: 'TN',
  texas: 'TX',
  utah: 'UT',
  vermont: 'VT',
  virginia: 'VA',
  washington: 'WA',
  'west virginia': 'WV',
  wisconsin: 'WI',
  wyoming: 'WY',
};

export const defaultStoreHours = {
  monday: {open: '', close: ''},
  tuesday: {open: '', close: ''},
  wednesday: {open: '', close: ''},
  thursday: {open: '', close: ''},
  friday: {open: '', close: ''},
  saturday: {open: '', close: ''},
  sunday: {open: '', close: ''},
};

export const getLocationDistance = (startLat: number, startLon: number, endLat: number, endLon: number) => {
  return getDistance({latitude: startLat, longitude: startLon}, {latitude: endLat, longitude: endLon}) / 1000;
};
