export enum RegexEnum {
  ROUTINGNUMBER = '^[0-9]*$',
  ROUTINGNUMBERMSG = 'Please enter a valid routing number',
  ACCOUNTNUMBER = '^[0-9]*$',
  ACCOUNTNUMBERMSG = 'Please enter a valid account number',
  ZIP = '^d{5}([-]|s*)?(d{4})?$',
  ZIPMSG = 'Please enter a valid Zip code',
  NEWPASSWORD = '^(?=.{6,}$)(?=.*?[a-z])(?=.*?[A-Z])(?=.*?[0-9])(?=.*?W)',
  NEWPASSWORDMSG = 'Your password must be 6 or more characters long and contain a mix of upper and lower case letters, a number and special character.',
  CONFIRMNEWPASSWORD = '^(?=.{6,}$)(?=.*?[a-z])(?=.*?[A-Z])(?=.*?[0-9])(?=.*?W)',
  CONFIRMNEWPASSWORDMSG = 'Your password must be 6 or more characters long and contain a mix of upper and lower case letters, a number and special character.',
  PHONENUMBER = '^(+d{1,2}s)?(?d{3})?[s.-]?d{3}[s.-]?d{4}$',
  PHONENUMBERMSG = 'Please enter a valid phone number',
  USERNAME = '^.{4,15}$',
  USERNAMEMSG = 'Username must be 4-15 characters long.',
  FIRSTNAME = '^[a-zA-Z ]+$',
  FIRSTNAMEMSG = 'First name can only consist of alphabetical characters',
  LASTNAME = '^[a-zA-Z ]+$',
  LASTNAMEMSG = 'Last name can only consist of alphabetical characters',
  // eslint-disable-next-line quotes
  EMAIL = "A[a-z0-9!#$%&'*+/=?^_‘{|}~-]+(?:.[a-z0-9!#$%&'*+/=?^_‘{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?z",
  EMAILMSG = 'Please provide a valid email address',
  PASSWORD = '^(?=.{6,}$)(?=.*?[a-z])(?=.*?[A-Z])(?=.*?[0-9])(?=.*?W)',
  PASSWORDMSG = 'Your password must be 6 or more characters long and contain a mix of upper and lower case letters, a number and special character.',
}
